development:
  adapter: postgresql
  encoding: unicode
  database: Urls_dev
  pool: 5
  username: rakesh
  password:
  host: localhost 

test:
  adapter: postgresql
  encoding: unicode
  database: Urls_test
  pool: 5
  username: rakesh
  password: 
  host: localhost